name: PR Source Code Check
on: ['push', 'pull_request']

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
          run_install: true
      - run: pnpm run lint:strict

  tsc:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
          run_install: true
      - run: pnpm run typecheck

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
          run_install: true
      - run: pnpm run format:check

  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
          run_install: true
      - run: yarn test
